### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Poussinou**
Commit made via Stringlate (I'm currently experimenting this app a lot)

### CODE REVIEW

**Comment by Poussinou** [comment]
Hum, that makes more sense to use the term "Privacy Friendly" after the name of the app in French. In my opinion, you cannot put Privacy Friendly first. Furthermore, I didn't translate it since the corresponding term in French is very long... It doesn't make sense to put this English expression first

**Comment by Poussinou** [comment]
But choice is yours. French people will also understand if Privacy Friendly is at the first place ;)

**Comment by Yonjuni** [comment]
@Poussinou A reason to put it first would be that the name of the app group is Privacy Friendly Apps ;-)

**Comment by Poussinou** [comment]
Yep I know and I like your approach :-) Do what you want, Privacy Friendly at the first place also works;)

**Comment by Yonjuni** [comment]
@Poussinou Can you put "Privacy Friendly" first, please?

**Comment by Poussinou** [comment]
Done

**Pull request merged**
